{
  description = "rip: move files to the freedesktop.org trash, across btrfs subvolumes and bind mounts";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs = { self, nixpkgs }:
    let
      lib = nixpkgs.lib;
      linux = [ "x86_64-linux" "aarch64-linux" ];
      forSystems = systems: f: lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      # Single source of truth for the package version: `cargo` and the
      # release tooling (`just release`) both read Cargo.toml directly.
      version = (lib.importTOML ./Cargo.toml).package.version;

      meta = {
        description = "Move files to the freedesktop.org trash, across btrfs subvolumes and bind mounts";
        mainProgram = "rip";
        platforms = lib.platforms.linux;
      };

      ripper = pkgs: pkgs.rustPlatform.buildRustPackage {
        pname = "ripper";
        inherit version;
        src = ./.;
        cargoLock.lockFile = ./Cargo.lock;
        nativeBuildInputs = [ pkgs.installShellFiles pkgs.makeWrapper ];
        # The sandbox tests need bwrap, user namespaces and btrfs; the build
        # sandbox has none of them. `just test` runs them on Linux.
        cargoTestFlags = [ "--bins" ];
        # All three completion scripts are static files (completions/), not
        # generated by running the built binary, so they install the same
        # way on a native or a cross build.
        postInstall = ''
          installShellCompletion --cmd rip \
            --bash completions/rip.bash \
            --zsh completions/_rip \
            --fish completions/rip.fish
        '';
        # fzf runs the picker; GNU cp makes cross-filesystem copies. Prefixed, so
        # another `cp` earlier on the user's PATH cannot change how rip copies.
        postFixup = ''
          wrapProgram $out/bin/rip --prefix PATH : ${lib.makeBinPath [ pkgs.coreutils pkgs.fzf ]}
        '';
        inherit meta;
      };

      # A standalone static binary for the GitHub release (.github/workflows/release.yml):
      # no PATH wrapping (the release tarball needs GNU coreutils and fzf on the
      # user's own PATH instead, documented in README.md) and no completions
      # install (the release packs completions/ itself).
      ripperStatic = pkgs: pkgs.pkgsStatic.rustPlatform.buildRustPackage {
        pname = "ripper";
        inherit version;
        src = ./.;
        cargoLock.lockFile = ./Cargo.lock;
        cargoTestFlags = [ "--bins" ];
        inherit meta;
      };
    in
    {
      packages = lib.recursiveUpdate
        (forSystems linux (pkgs: { default = ripper pkgs; ripper = ripper pkgs; }))
        { x86_64-linux.static = ripperStatic nixpkgs.legacyPackages.x86_64-linux; };
      checks = forSystems linux (pkgs: { build = ripper pkgs; });
      # darwin: editing, `cargo fmt` and `cargo generate-lockfile` on zakkart only.
      devShells = forSystems (linux ++ [ "aarch64-darwin" ]) (pkgs: {
        default = pkgs.mkShell {
          packages = with pkgs; [ cargo rustc clippy rustfmt rust-analyzer just ]
            # Sandbox tests: bwrap, btrfs subvolumes, `script` for terminals,
            # fish, fzf, and bash-completion for tests/completions.rs's
            # bash/zsh sandbox tests (zsh needs zsh/zpty and compinit; bash
            # needs `complete`/`compgen`/`compopt`, which plain `bash` is
            # built without -- bashInteractive first on PATH gives the
            # sandbox that bash instead of the plain one already on it).
            ++ lib.optionals stdenv.hostPlatform.isLinux [ bashInteractive bubblewrap btrfs-progs util-linux fish fzf zsh bash-completion ];
        };
      });
    };
}
